module.exports = {
  baseUrl: "https://iris-produtividade-app.vercel.app/",
  baseUrlLogin: "https://iris-produtividade-app.vercel.app/login",
  baseUrlRegister: "https://iris-produtividade-app.vercel.app/register",
  baseUrlPomodoro: "https://iris-produtividade-app.vercel.app/app/pomodoro",
  baseUrlProjects: "https://iris-produtividade-app.vercel.app/app/projects",
  baseUrlLabels: "https://iris-produtividade-app.vercel.app/app/labels",
  baseUrlMyProfile: "https://iris-produtividade-app.vercel.app/app/profile",
  baseUrlInbox: "https://iris-produtividade-app.vercel.app/app/inbox",
  baseUrlUpcoming: "https://iris-produtividade-app.vercel.app/app/upcoming",
  baseUrlComplete: "https://iris-produtividade-app.vercel.app/app/completed",
  baseUrlSettings: "https://iris-produtividade-app.vercel.app/app/settings",
  baseUrlChangelog: "https://iris-produtividade-app.vercel.app/app/changelog",
  baseUrlStorage: "https://iris-produtividade-app.vercel.app/app/storage",
  baseUrlReports: "https://iris-produtividade-app.vercel.app/app/reports",
  baseUrlCalendar: "https://iris-produtividade-app.vercel.app/app/calendar",
  env: {
    aliase: "iris",
  },
  layout: "desktop",
  viewportHeight: 768,
  viewportWidth: 1440,
};
